services:
  - type: web
    name: ridesharz-backend
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: SPRING_PROFILES_ACTIVE
        value: prod
